### ISSUE TITLE
Error handling (Safari)

### ISSUE THREAD

**Issue by raimohanska** [markwylde/workerbox#11]
I noticed that when the script run in Workerbox fails with an error, the error is not propagated back to the host when running in Safari. In Chrome and Firefox it seems to work just fine.

In Safari you'll see `Unhandled Promise Rejection: DataCloneError: The object can not be cloned.` in the browser console.

You can demostrate this at https://workerbox.net/ by, for example, inserting something syntactically incorrect into User Playground.

**Comment by markwylde** [comment]
Hi @raimohanska 

I've [just done](https://github.com/markwylde/workerbox/pull/12) a massive overhaul of the code, abstracting out the communication stuff and fixing recursive communication on the scope/arguments/return.

Part of this changed how errors work.

I didn't see the error before my updates, but I've just checked now on Safari and it seems to work okay. Would you mind double checking please?

**Comment by raimohanska** [comment]
Found some issues with serialization, which prevent me from using the latest version. See #14.

**Comment by markwylde** [comment]
v5 has just been released, so hopefully this is now fixed?

**Comment by raimohanska** [comment]
Tested with Safari today and it seems to work now. Thrown errors can be observed on the host side as expected. Great work, thanks!
