### ISSUE TITLE
This library injects a link to workerbox.net?

### ISSUE THREAD

**Issue by silesky** [markwylde/workerbox#27]
Thanks for writing this library -- very cool! Unfortunately, the fact that it injects a link to workerbox.net wherever is used is problematic (if it was published under GPL, that might make more sense, rather than MIT).  Can we turn this off?

<img width="597" alt="image" src="https://github.com/markwylde/workerbox/assets/5115498/c2469b28-111e-495a-90ea-d3d17e6afa85">

**Comment by markwylde** [comment]
I think this link could be removed if it's running on the same domain.

I put that link in there, because if you're running the server in [another domain](https://github.com/markwylde/workerbox?tab=readme-ov-file#separate-domain) then it will appear in the network tab and people might not understand why.

In theory, it doesn't even need to be a link, but I wanted to avoid putting a bunch of explanation text in there as it would increase the page load.

The MIT license has less restrictions than the GPL, so I'm not sure what that would solve. However, happy to dual license if you would prefer GPL.

**Comment by clibequilibrium** [comment]
> I think this link could be removed if it's running on the same domain.
> 
> I put that link in there, because if you're running the server in [another domain](https://github.com/markwylde/workerbox?tab=readme-ov-file#separate-domain) then it will appear in the network tab and people might not understand why.
> 
> In theory, it doesn't even need to be a link, but I wanted to avoid putting a bunch of explanation text in there as it would increase the page load.
> 
> The MIT license has less restrictions than the GPL, so I'm not sure what that would solve. However, happy to dual license if you would prefer GPL.

Thank you four your work. Totally unrelated to the OP topic , but I am using workerbox in a collaborative web platform where users can write extensions for 3D experiences. Do you happen to see any potential drawbacks using a web worker + iframe per plugin / extension ? My use case is kind of Figma but for 3D so workerbox does look like the perfect use case. 

Reference: https://www.figma.com/blog/how-we-built-the-figma-plugin-system/

**Comment by markwylde** [comment]
> > I think this link could be removed if it's running on the same domain.
> > I put that link in there, because if you're running the server in [another domain](https://github.com/markwylde/workerbox?tab=readme-ov-file#separate-domain) then it will appear in the network tab and people might not understand why.
> > In theory, it doesn't even need to be a link, but I wanted to avoid putting a bunch of explanation text in there as it would increase the page load.
> > The MIT license has less restrictions than the GPL, so I'm not sure what that would solve. However, happy to dual license if you would prefer GPL.
> 
> Thank you four your work. Totally unrelated to the OP topic , but I am using workerbox in a collaborative web platform where users can write extensions for 3D experiences. Do you happen to see any potential drawbacks using a web worker + iframe per plugin / extension ? My use case is kind of Figma but for 3D so workerbox does look like the perfect use case.
> 
> Reference: https://www.figma.com/blog/how-we-built-the-figma-plugin-system/

Hi @clibequilibrium 

I think running a new web worker for each extension is smart. If the user installed two extensions, then each extension may be able to access each others context. So it's best to keep each in isolate through a new web worker instance.
