### ISSUE TITLE
Related project

### ISSUE THREAD

**Issue by manuel** [markwylde/workerbox#3]
Hello, I've built something similar: https://github.com/manuel/fully-isolated-web-workers

It uses a null-origin IFRAME as sandbox (to prevent access to same-origin resources like IndexedDB).

Inside the IFRAME, I set a CSP of "default-src 'none'" to prevent network access.

**Comment by markwylde** [comment]
It looks awesome manuel, and really simple. I've just done a huge overhall and managed to remove the `allow-same-origin` too, so finally IndexedDB can't be accessed.

Your repo's nicely documentation, and simple with the two html files too. Really like it :)
