### ISSUE TITLE
Using globals

### ISSUE THREAD

**Issue by raimohanska** [markwylde/workerbox#8]
In my use case, it would be optimal to be able to evaluate code in a global context instead of running within a wrapper function. This would allow the evaluated code to create global mutable variables for storing some state inside the sandbox, between code evaluations.

I'm building a coding game, where the user's code is supposed to declare a function called `decide` which will then be called by the game consecutively for new game state on each game step. It would be beneficial that that the user-supported code would also declare global mutable variables that it could use to store some state between game steps.

My suggestion for the API:

```typescript
function createWorkerBox(
  scriptUrl: string,
  options?: WorkerBoxOptions
): Promise<WorkerBox>;

type WorkerBoxOptions = {
  appendVersion: boolean;
  randomiseSubdomain: boolean;
};

type WorkerBox = {
  run: (code: string, scope?: Scope) => Promise<any>;
  runGlobal (code: string) => Promise<any>;
  destroy: () => Promise<void>;
}
```

The changes are that

1. the result of `createWorkerBox` is an object instead of a function
2. introduce separate `run` and `runGlobal` methods int the WorkerBox, where the former is similar to the current implementation, while the latter is run in a global scope

This is just a quick idea/suggestion and the API code has not been passed to a TypeScript compiler. Does this sound like something that would make sense? If you think this is feasible and agreeable, I could make a Pull Request soonish next week.

**Comment by markwylde** [comment]
I wonder would something like this work?

```javascript
let globalState = {
  a: 1
};

const scope = {
  getGlobalState: () => globalState,
  setGlobalState: ({newState}) => {
    globalState = { ...globalState, ...newState };
    return globalState;
  }
};

const result = await run(`
  const state = getGlobalState();

  setGlobalState({a: 2})
`, scope);
```

This way you are specifically telling the API how to handle global state and there's no leaky/accidental global stuff left behind?

Sorry if I've misunderstood the issue :)

**Comment by markwylde** [comment]
Or in your use case, maybe this?

```javascript
let decider;

const scope = {
  getDecider: (fn) => decider,
  setDecider: (newDecider) => {
     decider = newDecider
  }
};

const result = await run(`
  setDecider(name => name === 'Mark')
`, scope);
```

**Comment by markwylde** [comment]
Okay there may be a bug actually. The returned value is never actually resolved to the parent. I'll have a look at fixing this.

![image](https://user-images.githubusercontent.com/5929807/202910178-f197ea44-a4ed-4245-af3e-c56b6196317a.png)

**Comment by raimohanska** [comment]
i agree that preventing global namespace pollution is generally something to avoid. 

I also concur that this explicit state mgmt is a viable option. 

The game is intended for beginnner javascripters though, so it would be best approacable if they could use globals just like on any <script>. Therefore the option to run in global context would be preferred.

The option would also make this lib more generally applicable for similar use cases.

If backwards compatibility is preferred, that can be accomplished easily too - similarly to how I added the destroy method.

**Comment by raimohanska** [comment]
I’m glad you found the bug!

**Comment by markwylde** [comment]
Hey @raimohanska. I've just done a big refactor and I think it should be easier to do this now, by using globalThis within the same workerbox instance.

See the following tests:
- [same workerbox instance should share self](https://github.com/markwylde/workerbox/blob/master/test/suite.js#L26)
- [two workerbox instances do not share globalThis](https://github.com/markwylde/workerbox/blob/master/test/suite.js#L46)

But I do think if you want to share state between two different workerbox's, it should be implemented on functions in the scope.

**Comment by raimohanska** [comment]
Looks really good at a glance. I'm impressed by your automatic tests 👍. I'll check how this works in my application and report back.

**Comment by markwylde** [comment]
Thanks @raimohanska. It was _**really**_ hard getting those tests setup.

**Comment by markwylde** [comment]
Hopefully this is solved now, as globalThis is now shared between runs on the same instance.

If not happy to reopen.
